# Generated by Django 5.2.6 on 2025-10-29 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BOEDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boe_id", models.CharField(max_length=255, unique=True)),
                ("title", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("raw_html", models.TextField(blank=True)),
                ("raw_text", models.TextField(blank=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="boe", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BOEUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("articles_ingested", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="IngestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=32)),
                ("message", models.TextField(blank=True)),
                ("processed", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BOEArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("heading", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("section", models.CharField(blank=True, max_length=100, null=True)),
                ("start_offset", models.IntegerField(default=0)),
                ("end_offset", models.IntegerField(default=0)),
                ("indexed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified", models.BooleanField(default=False)),
                ("source_url", models.URLField(blank=True, null=True)),
                (
                    "normative_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="boe.boedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["article_number"], name="boe_boearti_article_4fff83_idx"
                    ),
                    models.Index(
                        fields=["indexed"], name="boe_boearti_indexed_293139_idx"
                    ),
                ],
            },
        ),
    ]
