# Generated by Django 5.2.6 on 2025-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CendojDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("court", models.CharField(blank=True, max_length=255, null=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                (
                    "decision_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("subject", models.CharField(blank=True, max_length=400, null=True)),
                ("parties", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("raw_xml", models.TextField(blank=True, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
