# Generated by Django 5.2.6 on 2025-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOEUpdateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("articles_ingested", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
