# Generated by Django 5.0.14 on 2025-07-06 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "source_website",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The website where the user engaged from",
                        verbose_name="source website",
                    ),
                ),
                (
                    "privacy_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user accepted privacy policy",
                        verbose_name="privacy policy accepted",
                    ),
                ),
                (
                    "terms_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user accepted terms of service",
                        verbose_name="terms accepted",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user accepted privacy and terms",
                        null=True,
                        verbose_name="accepted at",
                    ),
                ),
                (
                    "first_interaction",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user first interacted with the widget",
                        verbose_name="first interaction",
                    ),
                ),
                (
                    "last_interaction",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Most recent interaction with the widget",
                        verbose_name="last interaction",
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of questions asked",
                        verbose_name="total questions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this engagement user is active",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "User Engagement",
                "verbose_name_plural": "User Engagements",
                "db_table": "widget_user_engagement",
                "indexes": [
                    models.Index(fields=["email"], name="widget_user_email_ae6c45_idx"),
                    models.Index(
                        fields=["created_at"], name="widget_user_created_ae4bfe_idx"
                    ),
                    models.Index(
                        fields=["source_website"], name="widget_user_source__c2977c_idx"
                    ),
                ],
            },
        ),
    ]
