# Generated by Django 5.2.6 on 2025-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("professional", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                default="basic",
                max_length=32,
            ),
        ),
    ]
