# Generated by Django 5.2.6 on 2025-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatlog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="response_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="validations",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
