"""Create chat models for sessions and messages

Revision ID: be4583ab5e21
Revises: a3ad0a97aae6
Create Date: 2025-07-08 03:33:29.603051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4583ab5e21'
down_revision: Union[str, None] = 'a3ad0a97aae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
