# Generated by Django 5.2.6 on 2025-10-21 17:33

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticCacheEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("query_text", models.TextField()),
                ("response_text", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("tokens", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation_id"],
                        name="semantic_ca_convers_337f2d_idx",
                    ),
                    models.Index(
                        fields=["user"], name="semantic_ca_user_id_a3492f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="semantic_ca_created_612581_idx"
                    ),
                    models.Index(
                        fields=["fingerprint"], name="semantic_ca_fingerp_3a743e_idx"
                    ),
                ],
            },
        ),
    ]
