# Generated by Django 5.0.14 on 2025-07-02 22:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField(help_text="User's question")),
                (
                    "answer",
                    models.TextField(help_text="AI-generated response with citations"),
                ),
                (
                    "citations",
                    models.JSONField(
                        default=list,
                        help_text="List of legal article citations used in the answer",
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        help_text="Response generation time in milliseconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o",
                        help_text="OpenAI model used for generation",
                        max_length=50,
                    ),
                ),
                (
                    "retrieved_articles",
                    models.JSONField(
                        default=list,
                        help_text="List of article IDs retrieved from vector search",
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User satisfaction rating (1-5)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Log",
                "verbose_name_plural": "Chat Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated or user-defined session title",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CostMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(help_text="Number of tokens in the prompt"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(help_text="Number of tokens in the completion"),
                ),
                (
                    "embedding_tokens",
                    models.IntegerField(
                        default=0, help_text="Number of tokens used for embeddings"
                    ),
                ),
                (
                    "cost_eur",
                    models.DecimalField(
                        decimal_places=6, help_text="Total cost in EUR", max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt_cost_eur",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Cost of prompt tokens in EUR",
                        max_digits=10,
                    ),
                ),
                (
                    "completion_cost_eur",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Cost of completion tokens in EUR",
                        max_digits=10,
                    ),
                ),
                (
                    "embedding_cost_eur",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Cost of embedding tokens in EUR",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Metric",
                "verbose_name_plural": "Cost Metrics",
                "ordering": ["-created_at"],
            },
        ),
    ]
