# Generated by Django 5.0.14 on 2025-07-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="costmetric",
            name="chat_log",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_metric",
                to="chat.chatlog",
            ),
        ),
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(
                fields=["created_at"], name="chat_chatlo_created_97ea67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(
                fields=["session", "created_at"], name="chat_chatlo_session_3fe8e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costmetric",
            index=models.Index(
                fields=["created_at"], name="chat_costme_created_b0c0dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costmetric",
            index=models.Index(
                fields=["cost_eur"], name="chat_costme_cost_eu_14e2db_idx"
            ),
        ),
    ]
