# Generated by Django 5.0.14 on 2025-07-01 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "law",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the law (e.g., 'Ley del IVA', 'Ley del IRPF')",
                        max_length=200,
                    ),
                ),
                (
                    "article_num",
                    models.CharField(
                        help_text="Article number (e.g., '21', '21.1', '21 bis')",
                        max_length=50,
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Full text content of the article"),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="Direct BOE URL to the article", max_length=500
                    ),
                ),
                (
                    "sync_ts",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the article was last synchronized",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Article title if available",
                        max_length=500,
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last modification date from BOE",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this article is currently in force",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Article",
                "verbose_name_plural": "Legal Articles",
                "ordering": ["law", "article_num"],
                "indexes": [
                    models.Index(
                        fields=["law", "article_num"], name="legal_legal_law_d2a294_idx"
                    ),
                    models.Index(
                        fields=["sync_ts"], name="legal_legal_sync_ts_72b60b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="legalarticle",
            constraint=models.UniqueConstraint(
                fields=("law", "article_num"), name="unique_law_article"
            ),
        ),
    ]
