# Generated by Django 5.0.14 on 2025-07-02 22:57

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbeddingSearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField(help_text="The search query")),
                (
                    "query_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("similarity_threshold", models.FloatField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "embedding_search_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=1000)),
                (
                    "document_type",
                    models.CharField(
                        help_text="Type of legal document (e.g., 'VAT Law', 'IRPF Law')",
                        max_length=100,
                    ),
                ),
                ("total_pages", models.IntegerField(blank=True, null=True)),
                ("total_chunks", models.IntegerField(default=0)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "legal_documents",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Sequential index of this chunk within the document"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual text content of this chunk"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 hash of content for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "page_numbers",
                    models.JSONField(
                        default=list, help_text="Page numbers this chunk spans"
                    ),
                ),
                (
                    "start_char",
                    models.IntegerField(
                        blank=True,
                        help_text="Starting character position in document",
                        null=True,
                    ),
                ),
                (
                    "end_char",
                    models.IntegerField(
                        blank=True,
                        help_text="Ending character position in document",
                        null=True,
                    ),
                ),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Vector embedding of the content",
                        null=True,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(default="text-embedding-3-small", max_length=100),
                ),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="rag_app.legaldocument",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="document_ch_documen_15f3c0_idx",
                    ),
                    models.Index(
                        fields=["content_hash"], name="document_ch_content_789e15_idx"
                    ),
                ],
            },
        ),
    ]
