# Generated by Django 5.0.14 on 2025-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legaldocument",
            options={"ordering": ["-publication_date", "title"]},
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="boe_number",
            field=models.CharField(
                blank=True,
                help_text="BOE number (e.g., BOE-A-2023-12345)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="boe_section",
            field=models.CharField(
                blank=True,
                help_text="BOE section (e.g., 'I. Disposiciones generales')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="document_name",
            field=models.CharField(
                blank=True,
                help_text="Official document name",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="effective_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the law/regulation became effective",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="issuing_authority",
            field=models.CharField(
                blank=True,
                help_text="Authority that issued the document",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="legal_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("modified", "Modified"),
                    ("repealed", "Repealed"),
                    ("superseded", "Superseded"),
                    ("unknown", "Unknown"),
                ],
                default="active",
                help_text="Current legal status of the document",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="publication_date",
            field=models.DateField(
                blank=True, help_text="Official publication date", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["document_type", "publication_date"],
                name="legal_docum_documen_1c9d44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["boe_number"], name="legal_docum_boe_num_ad496d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["legal_status", "publication_date"],
                name="legal_docum_legal_s_0d4648_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["publication_date"], name="legal_docum_publica_081601_idx"
            ),
        ),
    ]
