# Generated by Django 5.0.14 on 2025-07-06 15:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rag_app",
            "0002_alter_legaldocument_options_legaldocument_boe_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldocument",
            name="boe_id",
            field=models.CharField(
                blank=True,
                help_text="BOE document ID for API items",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department that issued the document",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="metadata",
            field=models.JSONField(
                blank=True, help_text="Additional metadata for API items", null=True
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="section",
            field=models.CharField(
                blank=True, help_text="BOE section name", max_length=200, null=True
            ),
        ),
        migrations.CreateModel(
            name="CaptureLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capture_date", models.DateField(help_text="Date of the BOE capture")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "documents_found",
                    models.IntegerField(
                        default=0, help_text="Number of documents found from API"
                    ),
                ),
                (
                    "documents_downloaded",
                    models.IntegerField(
                        default=0, help_text="Number of documents downloaded"
                    ),
                ),
                (
                    "documents_processed",
                    models.IntegerField(
                        default=0, help_text="Number of documents processed"
                    ),
                ),
                (
                    "embeddings_created",
                    models.IntegerField(
                        default=0, help_text="Number of embeddings created"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "api_items_processed",
                    models.IntegerField(
                        default=0, help_text="Number of API items processed"
                    ),
                ),
                (
                    "pdf_files_processed",
                    models.IntegerField(
                        default=0, help_text="Number of PDF files processed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "capture_logs",
                "ordering": ["-capture_date", "-started_at"],
                "indexes": [
                    models.Index(
                        fields=["capture_date"], name="capture_log_capture_96e314_idx"
                    ),
                    models.Index(
                        fields=["status", "capture_date"],
                        name="capture_log_status_279c26_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="capture_log_started_471ee8_idx"
                    ),
                ],
                "unique_together": {("capture_date", "started_at")},
            },
        ),
    ]
