# Generated by Django 5.2.6 on 2025-10-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="credits",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="plan",
            field=models.CharField(default="free", max_length=20),
        ),
    ]
