# Generated by Django 5.2.6 on 2025-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_credits_alter_userprofile_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="credits",
            field=models.IntegerField(default=500),
        ),
    ]
