# Generated by Django 5.2.6 on 2025-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userprofile_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="credits",
            field=models.IntegerField(default=5),
        ),
    ]
