"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations = {
  es: {
  "sidebar.settings": "Configuración",
    // Navigation
    "nav.chat": "Chat",
    "nav.analytics": "Analíticas",
    "nav.history": "Historial",
    "nav.search": "Buscar",
    "nav.signin": "Iniciar Sesión",
    "nav.signup": "Regístrate",

    // Hero Section
    "hero.badge": "🤖 Asistente Fiscal IA para Profesionales Culturales",
    "hero.title": "Asesoramiento Fiscal Inteligente",
    "hero.subtitle": "para Mentes Creativas",
    "hero.description":
      "Asesoramiento fiscal inteligente para profesionales culturales españoles. Respuestas precisas basadas en la legislación española actual.",
    "hero.cta.primary": "Comenzar Consulta",
    "hero.cta.secondary": "Saber Más →",

    // Trust Indicators
    "trust.verified": "Opiniones legales verificadas del BOE",
    "trust.availability": "Disponibilidad 24/7",
    "trust.updated": "Actualizado con las últimas regulaciones",
    "trust.specialized": "Especializado para autónomos",

    // Stats
    "stats.laws": "Leyes analizadas",
    "stats.articles": "Artículos indexados",
    "stats.accuracy": "Precisión",
    "stats.availability": "Disponibilidad",

    // Why Choose Section
    "why.title": "¿Por qué elegir ARTISTING?",
    "why.subtitle":
      "Construido específicamente para profesionales culturales españoles con respuestas precisas y respaldadas legalmente",
    "why.legislation.title": "Respuestas basadas en legislación actual",
    "why.legislation.desc": "Información actualizada del BOE",
    "why.specialized.title": "Especializado en profesionales culturales",
    "why.specialized.desc": "Conocimiento específico del sector",
    "why.instant.title": "Respuestas instantáneas con IA",
    "why.instant.desc": "Análisis rápido y preciso",
    
    //Chat Popup
    "chat.credits.title": "Has agotado tus créditos de prueba.",
    "chat.credits.message": "Activa tu suscripción para seguir recibiendo asistencia legal profesional para el sector cultural y creativo.",
    "chat.credits.subscribe": "Suscribirse Ahora",
    "chat.credits.dismiss": "Cerrar",

    // Frequent Questions
    "faq.title": "Preguntas Frecuentes",
    "faq.subtitle": "Obtén respuestas instantáneas a preguntas fiscales comunes",
    "faq.vat.title": "IVA para autónomos",
    "faq.vat.desc": "Consultoría sobre facturación y declaraciones de IVA",
    "faq.irpf.title": "Deducciones IRPF",
    "faq.irpf.desc": "Gastos deducibles para profesionales culturales",
    "faq.international.title": "Facturación internacional",
    "faq.international.desc": "Regulaciones para servicios en el extranjero",
    "faq.objective.title": "Estimación objetiva",
    "faq.objective.desc": "Módulos vs estimación directa",

    // Badges
    "badge.popular": "Popular",
    "badge.essential": "Esencial",
    "badge.advanced": "Avanzado",
    "badge.recommended": "Recomendado",

    // Testimonials
    "testimonials.title": "Confiado por Profesionales",
    "testimonials.subtitle": "Ve lo que dicen los profesionales culturales sobre ARTISTING",
    "testimonials.maria":
      "ARTISTING me ayudó a entender los requisitos de IVA para clientes internacionales. Me ahorró horas de investigación.",
    "testimonials.carlos":
      "Finalmente, asesoramiento fiscal que entiende el sector cultural. Las citas siempre son precisas.",
    "testimonials.ana":
      "Las respuestas instantáneas con referencias legales me dan confianza en mis decisiones fiscales.",
    "testimonials.maria.role": "Diseñadora Freelance",
    "testimonials.carlos.role": "Músico Independiente",
    "testimonials.ana.role": "Creadora de Contenido",

    // Final CTA
    "cta.title": "¿Listo para resolver tus preguntas fiscales?",
    "cta.description":
      "Nuestro asistente IA está específicamente entrenado para el sector cultural español y te proporcionará respuestas precisas basadas en la legislación actual.",
    "cta.button": "Comenzar Ahora →",

    // Footer
    "footer.description":
      "Asistente legal IA especializado en legislación fiscal española para profesionales culturales.",
    "footer.product": "Producto",
    "footer.features": "Características",
    "footer.pricing": "Precios",
    "footer.api": "API",
    "footer.documentation": "Documentación",
    "footer.legal": "Legal",
    "footer.terms": "Términos de Servicio",
    "footer.privacy": "Política de Privacidad",
    "footer.cookies": "Cookies",
    "footer.gdpr": "GDPR",
    "footer.support": "Soporte",
    "footer.help": "Centro de Ayuda",
    "footer.contact": "Contacto",
    "footer.status": "Estado del Servicio",
    "footer.community": "Comunidad",
    "footer.rights": "Todos los derechos reservados.",

    // Chat Page
    "chat.title": "Consulta Legal IA",
    "chat.subtitle": "Especializado en legislación fiscal española",
    "chat.credits.remaining": "Créditos restantes",
    "chat.sidebar.chat": "Chat Legal",
    "chat.sidebar.credits": "Mis Créditos",
    "chat.sidebar.docs": "Documentos Legales",
    "chat.sidebar.history": "Historial de Chat",
    "chat.sidebar.account": "Configuración de Cuenta",
    "chat.sidebar.settings": "Preferencias",
    "chat.sidebar.help": "Ayuda y Soporte",
    "chat.sidebar.analytics": "Análisis de Uso",
    "chat.sidebar.payment": "Pagos y Facturación",
    "chat.sidebar.status": "Estado del Sistema",
    "chat.sidebar.logout": "Cerrar Sesión",
    "chat.welcome.title": "¿En qué puedo ayudarte hoy?",
    "chat.welcome.description":
      "Soy tu asistente contable, fiscal, laboral y legal especializado en el sector cultural y creativo y estoy aquí para resolver tus consultas.",
    "chat.welcome.examples": "Tan solo necesito que me indiques quién eres, a qué te dedicas y cuál es la consulta quedeseas resolver. No obstante, cuanta más información aportes, más completa será la respuesta que recibirás.",
    "chat.input.placeholder": "Escribe tu consulta legal aquí...",
    "chat.sidebar.view_plans": "Ver planes",
    "chat.input.analyzing": "",
    "chat.input.nocredits": "Sin créditos restantes.",
    "chat.input.buycredits": "Comprar más créditos",
    "chat.input.disclaimer": "La información proporcionada por ARTISTING es de carácter informativo y debe ser revisada por un profesional antes de ser utilizada.",
    "chat.examples.freelancer": "¿Cómo debo facturar como freelancer cultural?",
    "chat.examples.vat": "¿Qué IVA aplico a mis servicios artísticos?",
    "chat.examples.deductions": "¿Puedo deducir gastos de material artístico en IRPF?",
    "chat.error.failed": "Error al enviar mensaje. Por favor intente nuevamente.",
    "chat.error.question_too_short": "La pregunta es muy corta. Por favor proporcione más detalles.",
    "chat.examples.copyright": "¿Cómo tributan los derechos de autor?",
    "chat.examples.obligations": "¿Qué obligaciones tengo como autónomo cultural?",
    "chat.header.new_chat": "Nueva Consulta",

    // Credits Page
    "credits.title": "Gestión de Créditos",
    "credits.subtitle": "Administra tus créditos y consulta tu historial de uso",
    "credits.current.status": "Estado Actual de Créditos",
    "credits.used": "Créditos utilizados",
    "credits.renewal": "Renovación",
    "credits.history.title": "Historial de Uso Reciente",
    "credits.history.subtitle": "Tus últimas consultas legales",
    "credits.purchase.title": "Comprar Créditos",
    "credits.purchase.subtitle": "Elige el paquete que mejor se adapte a tus necesidades",
    "credits.per.credit": "por crédito",
    "credits.select.plan": "Por favor selecciona un plan",
    "credits.purchase": "Comprar Ahora",
    "credits.purchase.success": "¡Compra exitosa!",
    "credits.purchase.error": "Error en la compra",
    "credits.upgrade.button": "Ver Planes",
    "credits.verifying.payment": "Verificando el pago...",
    "credits.payment.success.title": "¡Pago exitoso!",
    "credits.payment.success.message": "Tu pago ha sido procesado. Los créditos se han añadido a tu cuenta.",
    "credits.payment.failed.title": "Error en el pago",
    "credits.payment.failed.message": "Lo sentimos, hubo un problema al procesar el pago.",
    "credits.support.contact": "Contacta con soporte:",
    "credits.benefits.title": "Beneficios Incluidos",
    "credits.benefits.legal": "Respuestas con referencias legales",
    "credits.benefits.updated": "Acceso a legislación actualizada",
    "credits.benefits.support": "Soporte especializado",
    "credits.benefits.history": "Historial de consultas",
    "credits.benefits.no_commitment": "Sin compromisos a largo plazo",
    "credits.security.notice": "Pago seguro con cifrado SSL",

    // Analytics Page
    "analytics.title": "Panel de Analíticas",
    "analytics.subtitle": "Rastrea tus patrones de consulta legal y obtén insights",
    "analytics.overview": "Resumen",
    "analytics.consultations": "Consultas",
    "analytics.topics": "Temas",
    "analytics.trends": "Tendencias",
    "analytics.total.consultations": "Total de Consultas",
    "analytics.this.month": "Este Mes",
    "analytics.avg.response": "Tiempo Promedio de Respuesta",
    "analytics.satisfaction": "Tasa de Satisfacción",
    "analytics.popular.topics": "Temas Más Populares",
    "analytics.recent.activity": "Actividad Reciente",
    "analytics.consultation.trends": "Tendencias de Consultas",
    "analytics.topic.distribution": "Distribución de Temas",
    "analytics.monthly.usage": "Uso Mensual",

    // History Page
    "history.title": "Historial de Consultas",
    "history.subtitle": "Revisa tus consultas legales pasadas y respuestas",
    "history.search.placeholder": "Buscar consultas...",
    "history.filter.all": "Todos los Temas",
    "history.filter.vat": "IVA",
    "history.filter.irpf": "IRPF",
    "history.filter.billing": "Facturación",
    "history.filter.deductions": "Deducciones",
    "history.sort.newest": "Más Recientes",
    "history.sort.oldest": "Más Antiguos",
    "history.sort.relevant": "Más Relevantes",
    "history.no.results": "No se encontraron consultas",
    "history.load.more": "Cargar Más",
    "history.export": "Exportar Historial",

    // Account/Profile Page
    "account.title": "Configuración de Cuenta",
    "account.subtitle": "Gestiona tu perfil y preferencias",
    "account.profile": "Perfil",
    "account.billing": "Facturación",
    "account.security": "Seguridad",
    "account.notifications": "Notificaciones",
    "account.personal.info": "Información Personal",
    "account.first.name": "Nombre",
    "account.last.name": "Apellidos",
    "account.email": "Correo Electrónico",
    "account.phone": "Teléfono",
    "account.company": "Empresa",
    "account.profession": "Profesión",
    "account.save.changes": "Guardar Cambios",
    "account.change.password": "Cambiar Contraseña",
    "account.current.password": "Contraseña Actual",
    "account.new.password": "Nueva Contraseña",
    "account.confirm.password": "Confirmar Nueva Contraseña",
    "account.two.factor": "Autenticación de Dos Factores",
    "account.delete.account": "Eliminar Cuenta",
    "account.profile.saved": "¡Perfil actualizado correctamente!",
    "account.profile.save.error": "Error al actualizar el perfil",
    "account.password.changed": "¡Contraseña cambiada correctamente!",
    "account.password.change.error": "Error al cambiar la contraseña",
    "account.password.mismatch": "Las contraseñas no coinciden",
    "account.password.too.short": "La contraseña debe tener al menos 8 caracteres",

    // Credits & Payment
    "credits.usage.history": "Historial de Uso Reciente",
    "credits.buy.credits": "Comprar Créditos",
    "credits.auto.refill": "Recarga automática",
    "credits.payment.method": "Método de Pago",
    "credits.billing.history": "Historial de Facturación",
    "credits.invoice": "Factura",
    "credits.download": "Descargar",
    
    // Payment Page
    "payment.title": "Pago",
    "payment.subtitle": "Completa tu compra de créditos",
    "payment.order.summary": "Resumen del Pedido",
    "payment.payment.method": "Método de Pago",
    "payment.card.number": "Número de Tarjeta",
    "payment.expiry": "MM/AA",
    "payment.cvc": "CVC",
    "payment.cardholder": "Nombre del Titular",
    "payment.billing.address": "Dirección de Facturación",
    "payment.country": "País",
    "payment.postal.code": "Código Postal",
    "payment.complete.payment": "Completar Pago",
    "payment.secure": "Pago Seguro",
    "payment.processing": "Procesando...",
  // Pricing
  "pricing.badge": "Planes de Créditos",
  "pricing.title": "Precios",
  "pricing.subtitle": "Elige el plan que mejor se adapte a tus necesidades",
  "pricing.month": "mes",
  "pricing.credits": "créditos",
  "pricing.included": "Incluye",
  "pricing.limitations": "Limitaciones",
  "pricing.get.started": "Comenzar",
  "pricing.select": "Seleccionar Plan",
  "pricing.popular": "Popular",
  "pricing.upgrade.button": "Ver Planes",
  // Basic plan
  "pricing.basic.name": "Básico",
  "pricing.basic.description": "Ideal para freelancers y consultas ocasionales.",
  "pricing.basic.feature1": "50 créditos mensuales",
  "pricing.basic.feature2": "Respuestas basadas en legislación española",
  "pricing.basic.feature3": "Soporte por email",
  "pricing.basic.feature4": "Acceso al historial de consultas",
  "pricing.basic.limitation1": "Sin facturación avanzada",
  "pricing.basic.limitation2": "Sin prioridad de soporte",
  // Professional plan
  "pricing.professional.name": "Profesional",
  "pricing.professional.description": "Para profesionales que necesitan consultas frecuentes.",
  "pricing.professional.feature1": "200 créditos mensuales",
  "pricing.professional.feature2": "Soporte prioritario",
  "pricing.professional.feature3": "Facturación y factura disponible",
  "pricing.professional.feature4": "Acceso a análisis de uso",
  "pricing.professional.feature5": "Respuestas más detalladas",
  "pricing.professional.feature6": "Integraciones futuras",
  // Enterprise plan
  "pricing.enterprise.name": "Enterprise",
  "pricing.enterprise.description": "Solución para equipos y organizaciones.",
  "pricing.enterprise.feature1": "500 créditos mensuales",
  "pricing.enterprise.feature2": "Cuenta multi-usuario",
  "pricing.enterprise.feature3": "Soporte dedicado",
  "pricing.enterprise.feature4": "Integraciones personalizadas",
  "pricing.enterprise.feature5": "SLA por acuerdo",
  "pricing.enterprise.feature6": "Facturación avanzada",
  "pricing.enterprise.feature7": "Provisionamiento y onboarding",
  // Pricing FAQ
  "pricing.faq.title": "Preguntas sobre precios",
  "pricing.faq.subtitle": "Dudas comunes sobre nuestros planes",
  "pricing.faq.q1": "¿Puedo cambiar de plan más tarde?",
  "pricing.faq.a1": "Sí, puedes actualizar o degradar tu plan en cualquier momento desde la sección de facturación.",
  "pricing.faq.q2": "¿Hay facturas disponibles?",
  "pricing.faq.a2": "Sí, ofrecemos facturas para todos los pagos realizados en la plataforma.",
  "pricing.faq.q3": "¿Qué sucede si me quedo sin créditos?",
  "pricing.faq.a3": "Podrás comprar paquetes adicionales o cambiar a un plan superior.",
  "pricing.faq.q4": "¿Ofrecen reembolsos?",
  "pricing.faq.a4": "Los reembolsos se gestionan caso por caso según nuestra política de reembolsos.",

  // Forgot / Reset
  "forgot.title": "Recuperar Contraseña",
  "forgot.description": "Introduce tu correo y te enviaremos un enlace para restablecer tu contraseña.",
  "forgot.sending": "Enviando...",
  "forgot.send_link": "Enviar enlace de restablecimiento",
  "forgot.success": "Enlace enviado",
  "forgot.success_message": "Si existe una cuenta, recibirás un correo con el enlace para restablecer tu contraseña.",
  "forgot.error": "Error enviando el enlace",
  "forgot.remember": "¿Recordaste tu contraseña?",
  "forgot.email.placeholder": "tu@ejemplo.com",

  // Auth / Reset password keys
  "auth.reset.title": "Restablecer Contraseña",
  "auth.reset.token_required": "Se requiere un token en la URL",
  "auth.reset.request_new": "Solicitar nuevo enlace",
  "auth.reset.invalid_link": "Enlace inválido",
  "auth.reset.invalid_token_message": "El enlace de restablecimiento no es válido o ha caducado.",
  "auth.reset.link_expired": "El enlace ha expirado o es inválido.",
  "auth.reset.success": "Contraseña restablecida con éxito",
  "auth.reset.error": "Error al restablecer la contraseña",
  "auth.reset.resetting": "Restableciendo...",
  "auth.reset.submit": "Restablecer contraseña",
  "auth.reset.remember_password": "¿Recordaste tu contraseña?",

  // Password fields
  "auth.password.label": "Nueva contraseña",
  "auth.password.placeholder": "Introduce una contraseña segura",
  "auth.password.requirements": "Mínimo 8 caracteres.",
  "auth.password.confirm_label": "Confirmar contraseña",
  "auth.password.confirm_placeholder": "Repite la contraseña",
  // Additional payment strings used in UI text (ES)
  "payment.order.package": "{name} - {credits} créditos",
  "payment.order.total": "Total",
  "payment.features.immediate": "Acceso inmediato a créditos",
  "payment.features.no_commitment": "Sin compromisos a largo plazo",
  "payment.features.support": "Soporte especializado",
  "payment.features.invoice": "Factura disponible",
  "payment.security.notice.title": "Pago seguro",
  "payment.security.notice.desc": "Los pagos se procesan de forma segura por nuestro proveedor. No almacenamos los datos completos de su tarjeta.",

    // Settings
    "settings.title": "Configuración",
    "settings.general": "General",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.notifications": "Notificaciones",
    "settings.privacy": "Privacidad",
    "settings.data.export": "Exportar Datos",
    "settings.data.delete": "Eliminar Datos",
    "settings.data.export.success": "¡Datos exportados correctamente!",
    "settings.data.export.error": "Error al exportar datos",
    "settings.data.delete.success": "¡Datos eliminados correctamente!",
    "settings.data.delete.error": "Error al eliminar datos",
    "settings.data.delete.confirm": "¿Estás seguro de que quieres eliminar todos tus datos? Esta acción no se puede deshacer.",
    "settings.account.delete.success": "¡Cuenta eliminada correctamente!",
    "settings.account.delete.error": "Error al eliminar la cuenta",
    "settings.account.delete.confirm": "¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer.",

    // Auth Pages
    "auth.login.title": "INICIAR SESIÓN EN ARTISTING",
    "auth.login.subtitle": "Accede a la plataforma de referencia del sector cultural y creativo",
    "auth.login.email": "EMAIL",
    "auth.login.password": "CONTRASEÑA",
    "auth.login.show.password": "Mostrar contraseña",
    "auth.login.hide.password": "Ocultar contraseña",
    "auth.login.forgot.password": "¿Has Olvidado tu contraseña?",
    "auth.login.submit": "INICIAR SESIÓN",
    "auth.login.no.account": "¿Aún no tienes cuenta?",
    "auth.login.signup.link": "REGÍSTRATE AQUÍ",
    "auth.signup.title": "CREA TU CUENTA EN ARTISTING",
    "auth.signup.subtitle": "Únete a la plataforma de referencia del sector cultural y creativo",
    "auth.signup.first.name": "NOMBRE",
    "auth.signup.last.name": "APELLIDOS",
    "auth.signup.email": "EMAIL",
    "auth.signup.password": "CONTRASEÑA",
    "auth.signup.confirm.password": "CONFIRMAR CONTRASEÑA",
    "auth.signup.terms": "He leído y acepto los T&C",
    "auth.signup.submit": "CREA MI CUENTA",
    "auth.signup.have.account": "¿Ya tienes una cuenta?",
    "auth.signup.login.link": "INICIA SESIÓN AQUÍ",
    "auth.error.passwords.mismatch": "Las contraseñas no coinciden",
    "auth.error.accept.terms": "Debes aceptar los términos y condiciones",
    "auth.error.create.account": "Error al crear la cuenta",
    "auth.error.login.failed": "Error al iniciar sesión",
    "auth.login.success": "¡Sesión iniciada correctamente!",
    "auth.signup.success": "¡Cuenta creada exitosamente!",
    "auth.tagline": "Asistente Legal Inteligente",
    "auth.verifying_access": "Verificando acceso...",
    "auth.please_wait_session": "Por favor espera mientras verificamos tu sesión",

    // Privacy Policy
    "privacy.title": "Política de Privacidad",
    "privacy.last.updated": "Última actualización",
    "privacy.date": "1 de enero de 2024",
    "privacy.introduction.title": "Introducción",
    "privacy.introduction.content": "ARTISTING se compromete a proteger su privacidad y datos personales. Esta Política de Privacidad explica cómo recopilamos, usamos, almacenamos y protegemos su información cuando utiliza nuestros servicios de asistencia fiscal con IA.",
    "privacy.data.collection.title": "Recopilación de Datos",
    "privacy.data.collection.intro": "Recopilamos los siguientes tipos de información:",
    "privacy.data.collection.item1": "Información de cuenta (nombre, email, datos de facturación)",
    "privacy.data.collection.item2": "Datos de uso (preguntas realizadas, funciones utilizadas, duración de sesión)",
    "privacy.data.collection.item3": "Datos técnicos (dirección IP, tipo de navegador, información del dispositivo)",
    "privacy.data.collection.item4": "Datos de comunicación (solicitudes de soporte, comentarios)",
    "privacy.data.collection.item5": "Información de pago (procesada de forma segura a través de proveedores terceros)",
    "privacy.data.usage.title": "Cómo Usamos Sus Datos",
    "privacy.data.usage.intro": "Sus datos se utilizan para:",
    "privacy.data.usage.item1": "Proporcionar y mejorar nuestros servicios de asistencia fiscal con IA",
    "privacy.data.usage.item2": "Procesar pagos y gestionar su cuenta",
    "privacy.data.usage.item3": "Comunicarnos con usted sobre actualizaciones del servicio y soporte",
    "privacy.data.usage.item4": "Cumplir con obligaciones legales y prevenir fraudes",
    "privacy.data.sharing.title": "Compartir Datos",
    "privacy.data.sharing.content": "No vendemos sus datos personales. Podemos compartir datos con proveedores de servicios de confianza que nos ayudan a operar nuestros servicios, y solo cuando sea requerido por ley o para proteger nuestros derechos y la seguridad de los usuarios.",
    "privacy.data.security.title": "Seguridad de Datos",
    "privacy.data.security.content": "Implementamos medidas de seguridad estándar de la industria incluyendo cifrado, servidores seguros y auditorías de seguridad regulares para proteger sus datos del acceso no autorizado, alteración o destrucción.",
    "privacy.cookies.title": "Cookies y Seguimiento",
    "privacy.cookies.content": "Utilizamos cookies y tecnologías similares para mejorar su experiencia, analizar patrones de uso y proporcionar servicios personalizados. Puede controlar las preferencias de cookies a través de la configuración de su navegador.",
    "privacy.user.rights.title": "Sus Derechos",
    "privacy.user.rights.intro": "Bajo el RGPD y las leyes españolas de protección de datos, tiene derecho a:",
    "privacy.user.rights.item1": "Acceder a sus datos personales y solicitar copias",
    "privacy.user.rights.item2": "Corregir información inexacta o incompleta",
    "privacy.user.rights.item3": "Solicitar la eliminación de sus datos (derecho al olvido)",
    "privacy.user.rights.item4": "Restringir u oponerse al procesamiento de datos",
    "privacy.user.rights.item5": "Portabilidad de datos y retirada del consentimiento",
    "privacy.data.retention.title": "Retención de Datos",
    "privacy.data.retention.content": "Conservamos sus datos solo el tiempo necesario para proporcionar servicios y cumplir con obligaciones legales. Los datos de cuenta se conservan típicamente durante 3 años después del cierre de la cuenta, a menos que la ley requiera una retención más prolongada.",
    "privacy.international.title": "Transferencias Internacionales",
    "privacy.international.content": "Sus datos pueden ser procesados en países fuera de la UE. Aseguramos protección adecuada a través de salvaguardas apropiadas como Cláusulas Contractuales Estándar y decisiones de adecuación.",
    "privacy.changes.title": "Cambios en la Política",
    "privacy.changes.content": "Podemos actualizar esta Política de Privacidad periódicamente. Los cambios significativos se comunicarán por email y a través de nuestro servicio. El uso continuado después de los cambios indica aceptación de la política actualizada.",
    "privacy.contact.title": "Contáctanos",
    "privacy.contact.content": "Para preguntas relacionadas con la privacidad o para ejercer sus derechos, contacte a nuestro Oficial de Protección de Datos:",
    "privacy.back.home": "Volver al Inicio",

    // Cookies Policy
    "cookies.title": "Política de Cookies",
    "cookies.last.updated": "Última actualización",
    "cookies.date": "1 de enero de 2024",
    "cookies.what.are.title": "¿Qué son las Cookies?",
    "cookies.what.are.content": "Las cookies son pequeños archivos de texto almacenados en su dispositivo cuando visita nuestro sitio web. Nos ayudan a brindarle una mejor experiencia recordando sus preferencias y analizando cómo utiliza nuestro servicio.",
    "cookies.how.we.use.title": "Cómo Usamos las Cookies",
    "cookies.how.we.use.content": "Utilizamos cookies para mejorar su experiencia, proporcionar contenido personalizado, analizar el tráfico del sitio web y mejorar nuestros servicios. Todas las cookies se utilizan de acuerdo con las leyes de privacidad aplicables.",
    "cookies.types.title": "Tipos de Cookies que Utilizamos",
    "cookies.essential.name": "Cookies Esenciales",
    "cookies.essential.description": "Estas cookies son necesarias para que el sitio web funcione correctamente y no se pueden desactivar.",
    "cookies.essential.duration": "Sesión o hasta 1 año",
    "cookies.essential.example1": "Tokens de autenticación",
    "cookies.essential.example2": "Preferencias de seguridad",
    "cookies.essential.example3": "Configuración de idioma",
    "cookies.analytics.name": "Cookies de Análisis",
    "cookies.analytics.description": "Estas cookies nos ayudan a entender cómo los visitantes interactúan con nuestro sitio web.",
    "cookies.analytics.duration": "Hasta 2 años",
    "cookies.analytics.example1": "Google Analytics",
    "cookies.analytics.example2": "Estadísticas de uso",
    "cookies.analytics.example3": "Métricas de rendimiento",
    "cookies.functional.name": "Cookies Funcionales",
    "cookies.functional.description": "Estas cookies habilitan funcionalidad mejorada y personalización.",
    "cookies.functional.duration": "Hasta 1 año",
    "cookies.functional.example1": "Preferencias de tema",
    "cookies.functional.example2": "Historial de chat",
    "cookies.functional.example3": "Preferencias del usuario",
    "cookies.required": "Requeridas",
    "cookies.duration": "Duración",
    "cookies.examples": "Ejemplos",
    "cookies.third.party.title": "Cookies de Terceros",
    "cookies.third.party.content": "Podemos usar servicios de terceros que establecen sus propias cookies:",
    "cookies.third.party.item1": "Procesadores de pago para transacciones seguras",
    "cookies.third.party.item2": "Proveedores de análisis para información de uso",
    "cookies.third.party.item3": "Servicios de chat de soporte para asistencia al cliente",
    "cookies.manage.title": "Gestionar Cookies",
    "cookies.manage.content": "Puede controlar y gestionar las cookies a través de la configuración de su navegador. Tenga en cuenta que desactivar ciertas cookies puede afectar la funcionalidad del sitio web.",
    "cookies.browser.settings": "Configuración del Navegador",
    "cookies.browser.chrome": "Chrome: Configuración > Privacidad y Seguridad > Cookies",
    "cookies.browser.firefox": "Firefox: Configuración > Privacidad y Seguridad > Cookies",
    "cookies.browser.safari": "Safari: Preferencias > Privacidad > Cookies",
    "cookies.browser.edge": "Edge: Configuración > Privacidad > Cookies",
    "cookies.consent.title": "Consentimiento de Cookies",
    "cookies.consent.content": "Al continuar usando nuestro sitio web, consiente nuestro uso de cookies como se describe en esta política. Puede retirar el consentimiento en cualquier momento ajustando la configuración de su navegador.",
    "cookies.updates.title": "Actualizaciones de la Política",
    "cookies.updates.content": "Podemos actualizar esta Política de Cookies periódicamente. Cualquier cambio se publicará en esta página con una fecha de revisión actualizada.",
    "cookies.contact.title": "Contáctanos",
    "cookies.contact.content": "Si tiene preguntas sobre nuestro uso de cookies, contáctenos en privacy@ovra-ai.com.",
    "cookies.back.home": "Volver al Inicio",

    // GDPR
    "gdpr.title": "Cumplimiento RGPD",
    "gdpr.subtitle": "Sus derechos de protección de datos bajo la ley europea",
    "gdpr.what.is.title": "¿Qué es el RGPD?",
    "gdpr.what.is.content": "El Reglamento General de Protección de Datos (RGPD) es una ley integral de protección de datos que otorga a las personas control sobre sus datos personales y simplifica el entorno regulatorio para las empresas.",
    "gdpr.our.commitment.title": "Nuestro Compromiso",
    "gdpr.our.commitment.content": "ARTISTING está completamente comprometido con el cumplimiento del RGPD. Implementamos principios de privacidad por diseño y aseguramos que se respeten sus derechos de datos:",
    "gdpr.commitment.item1": "Procesamiento transparente de datos con consentimiento claro",
    "gdpr.commitment.item2": "Almacenamiento seguro de datos con cifrado y controles de acceso",
    "gdpr.commitment.item3": "Evaluaciones regulares de impacto en la privacidad",
    "gdpr.commitment.item4": "Procedimientos de notificación rápida de brechas",
    "gdpr.your.rights.title": "Sus Derechos de Datos",
    "gdpr.your.rights.subtitle": "Bajo el RGPD, tiene los siguientes derechos con respecto a sus datos personales:",
    "gdpr.right.access.title": "Derecho de Acceso",
    "gdpr.right.access.description": "Puede solicitar información sobre qué datos personales tenemos sobre usted.",
    "gdpr.right.access.action": "Contáctenos para solicitar una copia de sus datos",
    "gdpr.right.rectification.title": "Derecho de Rectificación",
    "gdpr.right.rectification.description": "Puede solicitar la corrección de datos personales inexactos o incompletos.",
    "gdpr.right.rectification.action": "Actualice su perfil o contacte soporte para correcciones",
    "gdpr.right.erasure.title": "Derecho de Supresión (Derecho al Olvido)",
    "gdpr.right.erasure.description": "Puede solicitar la eliminación de sus datos personales bajo ciertas circunstancias.",
    "gdpr.right.erasure.action": "Envíe una solicitud de eliminación a través de la configuración de su cuenta",
    "gdpr.right.portability.title": "Derecho a la Portabilidad de Datos",
    "gdpr.right.portability.description": "Puede solicitar sus datos en un formato estructurado y legible por máquina.",
    "gdpr.right.portability.action": "Exporte sus datos desde el panel de su cuenta",
    "gdpr.right.restriction.title": "Derecho a la Limitación del Tratamiento",
    "gdpr.right.restriction.description": "Puede solicitar limitación en cómo procesamos sus datos.",
    "gdpr.right.restriction.action": "Contacte a nuestro DPO para discutir restricciones de procesamiento",
    "gdpr.right.objection.title": "Derecho de Oposición",
    "gdpr.right.objection.description": "Puede oponerse a ciertos tipos de procesamiento de datos.",
    "gdpr.right.objection.action": "Opte por no participar a través de la configuración de cuenta o contacte soporte",
    "gdpr.how.to.exercise": "Cómo ejercer este derecho:",
    "gdpr.legal.basis.title": "Base Legal para el Procesamiento",
    "gdpr.legal.basis.content": "Procesamos sus datos personales basándose en los siguientes fundamentos legales:",
    "gdpr.legal.basis.item1": "Consentimiento: Para comunicaciones de marketing y funciones opcionales",
    "gdpr.legal.basis.item2": "Contrato: Para proporcionar nuestros servicios de asistencia fiscal",
    "gdpr.legal.basis.item3": "Interés Legítimo: Para mejora del servicio y prevención de fraudes",
    "gdpr.legal.basis.item4": "Obligación Legal: Para registros fiscales y requisitos de cumplimiento",
    "gdpr.data.transfers.title": "Transferencias Internacionales de Datos",
    "gdpr.data.transfers.content": "Cuando transferimos sus datos fuera de la UE, aseguramos protección adecuada a través de mecanismos aprobados como Cláusulas Contractuales Estándar y decisiones de adecuación de la Comisión Europea.",
    "gdpr.complaints.title": "Derecho a Presentar una Queja",
    "gdpr.complaints.content": "Si cree que no hemos manejado sus datos correctamente, tiene derecho a presentar una queja ante su autoridad supervisora local:",
    "gdpr.supervisory.authority": "Autoridad Supervisora Española",
    "gdpr.contact.dpo.title": "Contactar a Nuestro Oficial de Protección de Datos",
    "gdpr.contact.dpo.content": "Para cualquier pregunta relacionada con el RGPD o para ejercer sus derechos, contacte a nuestro Oficial de Protección de Datos:",
    "gdpr.response.time": "Responderemos a su solicitud dentro de 30 días",
    "gdpr.exercise.rights.title": "Ejercer Sus Derechos",
    "gdpr.exercise.rights.content": "¿Listo para ejercer sus derechos de protección de datos? Contáctenos o revise nuestra política de privacidad para más información.",
    "gdpr.contact.us": "Contáctanos",
    "gdpr.privacy.policy": "Política de Privacidad",
    "gdpr.back.home": "Volver al Inicio",

    // Help Center
    "help.title": "Centro de Ayuda",
    "help.subtitle": "Encuentre respuestas a sus preguntas y obtenga el soporte que necesita",
    "help.search.placeholder": "Buscar artículos de ayuda...",
    "help.search": "Buscar",
    "help.popular.title": "Artículos Populares",
    "help.popular.subtitle": "Temas de ayuda más consultados",
    "help.popular.article1": "Cómo comenzar con ARTISTING",
    "help.popular.article2": "Entender sus obligaciones fiscales como autónomo",
    "help.popular.article3": "Gestionar su cuenta y facturación",
    "help.popular.article4": "Interpretar respuestas de IA y asesoramiento legal",
    "help.popular.article5": "Privacidad y seguridad de datos",
    "help.categories.title": "Categorías de Ayuda",
    "help.categories.subtitle": "Explorar temas de ayuda por categoría",
    "help.getting.started.title": "Primeros Pasos",
    "help.getting.started.description": "Aprenda lo básico de usar ARTISTING",
    "help.getting.started.article1": "Crear su cuenta",
    "help.getting.started.article2": "Su primera consulta fiscal",
    "help.getting.started.article3": "Entender las respuestas de IA",
    "help.getting.started.article4": "Configurar su perfil",
    "help.billing.title": "Facturación y Suscripciones",
    "help.billing.description": "Gestione sus pagos y suscripción",
    "help.billing.article1": "Planes de suscripción y precios",
    "help.billing.article2": "Métodos de pago y facturación",
    "help.billing.article3": "Actualizar o degradar planes",
    "help.billing.article4": "Reembolsos y cancelaciones",
    "help.privacy.title": "Privacidad y Seguridad",
    "help.privacy.description": "Aprenda sobre protección de datos y seguridad",
    "help.privacy.article1": "Cómo protegemos sus datos",
    "help.privacy.article2": "Cumplimiento RGPD y sus derechos",
    "help.privacy.article3": "Política de cookies y preferencias",
    "help.privacy.article4": "Mejores prácticas de seguridad de cuenta",
    "help.account.title": "Gestión de Cuenta",
    "help.account.description": "Gestione la configuración y preferencias de su cuenta",
    "help.account.article1": "Actualizar información de perfil",
    "help.account.article2": "Cambiar su contraseña",
    "help.account.article3": "Configuración de idioma y notificaciones",
    "help.account.article4": "Eliminar su cuenta",
    "help.contact.title": "¿Aún Necesita Ayuda?",
    "help.contact.subtitle": "Póngase en contacto con nuestro equipo de soporte",
    "help.contact.chat": "Chat en Vivo",
    "help.contact.chat.description": "Chatee con nuestro equipo de soporte",
    "help.contact.chat.button": "Iniciar Chat",
    "help.contact.email": "Soporte por Email",
    "help.contact.email.description": "Envíenos un mensaje detallado",
    "help.contact.email.button": "Contáctanos",
    "help.contact.guides": "Guías de Usuario",
    "help.contact.guides.description": "Documentación detallada",
    "help.contact.guides.button": "Ver Guías",

    // Contact Page
    "contact.title": "Contáctanos",
    "contact.subtitle": "Póngase en contacto con nuestro equipo. Estamos aquí para ayudar con cualquier pregunta o inquietud.",
    "contact.form.title": "Envíanos un Mensaje",
    "contact.form.description": "Complete el formulario a continuación y nos pondremos en contacto con usted lo antes posible.",
    "contact.form.name": "Nombre Completo",
    "contact.form.name.placeholder": "Ingrese su nombre completo",
    "contact.form.email": "Dirección de Email",
    "contact.form.email.placeholder": "Ingrese su dirección de email",
    "contact.form.category": "Categoría",
    "contact.form.category.placeholder": "Seleccione una categoría",
    "contact.form.subject": "Asunto",
    "contact.form.subject.placeholder": "Breve descripción de su consulta",
    "contact.form.message": "Mensaje",
    "contact.form.message.placeholder": "Describa su pregunta o inquietud en detalle...",
    "contact.form.submit": "Enviar Mensaje",
    "contact.form.validation.required": "Por favor complete todos los campos requeridos",
    "contact.form.validation.email": "Por favor ingrese una dirección de email válida",
    "contact.form.success": "¡Mensaje enviado exitosamente! Nos pondremos en contacto pronto.",
    "contact.form.error": "Error al enviar mensaje. Por favor intente nuevamente.",
    "contact.category.general": "Consulta General",
    "contact.category.support": "Soporte Técnico",
    "contact.category.bug": "Reporte de Error",
    "contact.category.feature": "Solicitud de Función",
    "contact.info.title": "Información de Contacto",
    "contact.email.title": "Soporte por Email",
    "contact.email.description": "Envíenos un email en cualquier momento",
    "contact.email.action": "Típicamente respondemos dentro de 24 horas",
    "contact.phone.title": "Soporte Telefónico",
    "contact.phone.description": "Llámenos durante horario comercial",
    "contact.phone.action": "Lunes a Viernes, 9 AM - 6 PM CET",
    "contact.address.title": "Dirección de Oficina",
    "contact.address.description": "Visítenos en persona",
    "contact.address.action": "Solo con cita previa",
    "contact.hours.title": "Horario Comercial",
    "contact.hours.description": "Cuando estamos disponibles",
    "contact.hours.value": "Lunes - Viernes: 9:00 AM - 6:00 PM CET",
    "contact.faq.title": "Preguntas Frecuentes",
    "contact.faq.description": "Encuentre respuestas rápidas a preguntas comunes",
    "contact.faq.button": "Visitar Centro de Ayuda",

    // Status Page
    "status.title": "Estado del Servicio",
    "status.subtitle": "Monitoreo en tiempo real del estado y tiempo de actividad de todos los servicios de ARTISTING",
    "status.overall": "Estado General",
    "status.operational": "Operativo",
    "status.degraded": "Rendimiento Degradado",
    "status.outage": "Interrupción del Servicio",
    "status.resolved": "Resuelto",
    "status.services.title": "Estado de Servicios",
    "status.services.subtitle": "Estado actual de todos nuestros servicios",
    "status.service.api": "Servicio API",
    "status.service.api.description": "API principal para toda la funcionalidad de ARTISTING",
    "status.service.ai": "Procesamiento de IA",
    "status.service.ai.description": "Inferencia del modelo de IA y generación de respuestas",
    "status.service.database": "Base de Datos",
    "status.service.database.description": "Sistemas de almacenamiento y recuperación de datos",
    "status.service.web": "Aplicación Web",
    "status.service.web.description": "Aplicación web frontend e interfaz de usuario",
    "status.uptime": "Tiempo de Actividad",
    "status.response.time": "Tiempo de Respuesta",
    "status.incidents.title": "Incidentes Recientes",
    "status.incidents.subtitle": "Incidentes pasados y su estado de resolución",
    "status.incident.1.title": "Retrasos en Respuesta de IA",
    "status.incident.1.description": "Retrasos temporales en la generación de respuestas de IA debido a alta demanda",
    "status.incident.2.title": "Mantenimiento de Base de Datos",
    "status.incident.2.description": "El mantenimiento programado causó una breve interrupción del servicio",
    "status.duration": "Duración",
    "status.affected.services": "Servicios Afectados",
    "status.no.incidents.title": "Sin Incidentes Recientes",
    "status.no.incidents.description": "Todos los sistemas han estado funcionando sin problemas sin incidentes reportados en los últimos 30 días.",
    "status.subscribe.title": "Manténgase Actualizado",
    "status.subscribe.description": "Suscríbase a actualizaciones de estado y reciba notificaciones sobre cambios en el servicio",
    "status.subscribe.button": "Suscribirse a Actualizaciones",

    // Community Page
    "community.title": "Comunidad",
    "community.subtitle": "Únase a miles de profesionales culturales compartiendo conocimiento y experiencias",
    "community.join.button": "Unirse a la Comunidad",
    "community.explore.button": "Explorar Discusiones",
    "community.stats.members": "Miembros Activos",
    "community.stats.members.description": "Profesionales culturales en nuestra comunidad",
    "community.stats.discussions": "Discusiones",
    "community.stats.discussions.description": "Conversaciones y temas activos",
    "community.stats.resources": "Recursos Compartidos",
    "community.stats.resources.description": "Guías, plantillas y herramientas",
    "community.stats.experts": "Expertos Fiscales",
    "community.stats.experts.description": "Profesionales verificados proporcionando orientación",
    "community.platforms.title": "Únase a Nuestra Comunidad",
    "community.platforms.subtitle": "Conéctese con nosotros en su plataforma preferida",
    "community.discord.description": "Chat en tiempo real con colegas profesionales y expertos",
    "community.github.description": "Contribuya a herramientas y recursos de código abierto",
    "community.twitter.description": "Últimas actualizaciones y consejos rápidos",
    "community.linkedin.description": "Networking profesional e insights de la industria",
    "community.primary": "Principal",
    "community.members": "miembros",
    "community.join": "Unirse",
    "community.discussions.title": "Discusiones Destacadas",
    "community.discussions.subtitle": "Temas y conversaciones populares",
    "community.discussion.1.title": "Nuevas regulaciones de IVA para servicios digitales - Lo que necesita saber",
    "community.discussion.2.title": "Deducciones fiscales para autónomos: Guía completa para 2024",
    "community.discussion.3.title": "Configurar su primera factura como profesional cultural",
    "community.category.tax": "Asesoramiento Fiscal",
    "community.category.freelance": "Trabajo Autónomo",
    "community.category.legal": "Preguntas Legales",
    "community.by": "por",
    "community.view.all": "Ver Todas las Discusiones",
    "community.events.title": "Próximos Eventos",
    "community.events.subtitle": "Únase a nuestros webinars, talleres y sesiones de preguntas y respuestas",
    "community.event.1.title": "Taller de Planificación Fiscal para Profesionales Creativos",
    "community.event.2.title": "Entendiendo el IVA Español: Sesión Interactiva",
    "community.event.3.title": "Preguntas y Respuestas Mensual con Expertos Fiscales",
    "community.event.webinar": "Webinar",
    "community.event.workshop": "Taller",
    "community.event.qa": "Sesión de P&R",
    "community.registered": "registrados",
    "community.register": "Registrarse Ahora",
    "community.cta.title": "¿Listo para Unirse a Nuestra Comunidad?",
    "community.cta.description": "Conéctese con colegas profesionales, comparta experiencias y obtenga asesoramiento experto",
    "community.cta.join": "Unirse a la Comunidad",
    "community.cta.signup": "Registrarse en ARTISTING",

    // Terms of Service
    "terms.title": "Términos de Servicio",
    "terms.last.updated": "Última actualización",
    "terms.date": "1 de enero de 2024",
    "terms.back.home": "Volver al Inicio",
    "terms.acceptance.title": "Aceptación de Términos",
    "terms.acceptance.content": "Al acceder y utilizar los servicios de ARTISTING, acepta y se compromete a cumplir con los términos y disposiciones de este acuerdo. Si no está de acuerdo con lo anterior, por favor no utilice este servicio.",
    "terms.description.title": "Descripción del Servicio",
    "terms.description.content": "ARTISTING proporciona servicios de asistencia fiscal impulsados por IA específicamente diseñados para profesionales culturales españoles. Nuestro servicio ofrece orientación legal basada en la legislación española actual, incluyendo IVA, IRPF y otras regulaciones fiscales relevantes.",
    "terms.user.obligations.title": "Obligaciones del Usuario",
    "terms.user.obligations.intro": "Como usuario de ARTISTING, usted acepta:",
    "terms.user.obligations.item1": "Proporcionar información precisa y veraz al utilizar nuestros servicios",
    "terms.user.obligations.item2": "Utilizar el servicio solo para fines legales y de acuerdo con estos términos",
    "terms.user.obligations.item3": "No intentar eludir ninguna medida de seguridad o restricción de acceso",
    "terms.user.obligations.item4": "Respetar los derechos de propiedad intelectual de ARTISTING y terceros",
    "terms.intellectual.property.title": "Propiedad Intelectual",
    "terms.intellectual.property.content": "Todo el contenido, características y funcionalidad de ARTISTING, incluyendo pero no limitado a texto, gráficos, logotipos y software, son propiedad de ARTISTING y están protegidos por leyes internacionales de derechos de autor, marcas comerciales y otras leyes de propiedad intelectual.",
    "terms.privacy.title": "Privacidad y Protección de Datos",
    "terms.privacy.content": "Su privacidad es importante para nosotros. Nuestra Política de Privacidad explica cómo recopilamos, utilizamos, y protegemos su información cuando utiliza nuestros servicios. Al utilizar ARTISTING, usted consiente la recopilación y uso de información de acuerdo con nuestra Política de Privacidad.",
    "terms.payment.title": "Pago y Facturación",
    "terms.payment.content": "ARTISTING opera con un sistema basado en créditos. Los usuarios compran créditos para acceder a consultas de IA. Todos los pagos se procesan de forma segura, y los términos de facturación se muestran claramente antes de la compra. Los reembolsos están disponibles de acuerdo con nuestra política de reembolsos.",
    "terms.limitation.title": "Limitación de Responsabilidad",
    "terms.limitation.content": "ARTISTING proporciona información solo con fines educativos y de orientación. Aunque nos esforzamos por la precisión, nuestras respuestas de IA no deben reemplazar el asesoramiento legal profesional. Los usuarios son responsables de verificar la información y consultar con profesionales calificados para asuntos legales específicos.",
    "terms.termination.title": "Terminación",
    "terms.termination.content": "Nos reservamos el derecho de terminar o suspender su cuenta y acceso a nuestros servicios a nuestra sola discreción, sin previo aviso, por conducta que creamos que viola estos Términos de Servicio o es perjudicial para otros usuarios, nosotros o terceros.",
    "terms.changes.title": "Cambios en los Términos",
    "terms.changes.content": "Nos reservamos el derecho de modificar estos términos en cualquier momento. Notificaremos a los usuarios de cualquier cambio material por correo electrónico o a través de nuestro servicio. El uso continuado de ARTISTING después de los cambios constituye la aceptación de los nuevos términos.",
    "terms.contact.title": "Información de Contacto",
    "terms.contact.content": "Si tiene alguna pregunta sobre estos Términos de Servicio, por favor contáctenos:",
  },
  en: {
  "sidebar.settings": "Settings",
    // Mirror the Spanish structure with English translations
    "nav.chat": "Chat",
    "nav.analytics": "Analytics",
    "nav.history": "History",
    "nav.search": "Search",
    "nav.signin": "Sign in",
    "nav.signup": "Sign up",

    // Hero Section
    "hero.badge": "🤖 AI-Powered Tax Assistant for Cultural Professionals",
    "hero.title": "Smart Tax Advice",
    "hero.subtitle": "for Creative Minds",
    "hero.description":
      "Intelligent tax advice for Spanish cultural professionals. Accurate answers based on current Spanish legislation.",
    "hero.cta.primary": "Start Consultation",
    "hero.cta.secondary": "Learn More →",

    // Trust Indicators
    "trust.verified": "Verified legal opinions from BOE",
    "trust.availability": "24/7 availability",
    "trust.updated": "Updated with latest regulations",
    "trust.specialized": "Specialized for freelancers",

    // Stats
    "stats.laws": "Laws analyzed",
    "stats.articles": "Articles indexed",
    "stats.accuracy": "Accuracy",
    "stats.availability": "Availability",

    // Why Choose Section
    "why.title": "Why Choose ARTISTING?",
    "why.subtitle": "Built specifically for Spanish cultural professionals with accurate, legally-backed answers",
    "why.legislation.title": "Answers based on current legislation",
    "why.legislation.desc": "Information updated from BOE",
    "why.specialized.title": "Specialized in cultural professionals",
    "why.specialized.desc": "Specific knowledge of the sector",
    "why.instant.title": "Instant answers with AI",
    "why.instant.desc": "Fast and accurate analysis",

    // Frequent Questions
    "faq.title": "Frequent Questions",
    "faq.subtitle": "Get instant answers to common tax questions",
    "faq.vat.title": "VAT for freelancers",
    "faq.vat.desc": "Consulting on billing and VAT declarations",
    "faq.irpf.title": "IRPF deductions",
    "faq.irpf.desc": "Deductible expenses for cultural professionals",
    "faq.international.title": "International billing",
    "faq.international.desc": "Regulations for services abroad",
    "faq.objective.title": "Objective estimation",
    "faq.objective.desc": "Modules vs direct estimation",

    // Badges
    "badge.popular": "Popular",
    "badge.essential": "Essential",
    "badge.advanced": "Advanced",
    "badge.recommended": "Recommended",

    // Testimonials
    "testimonials.title": "Trusted by Professionals",
    "testimonials.subtitle": "See what cultural professionals say about ARTISTING",
    "testimonials.maria":
      "ARTISTING helped me understand VAT requirements for international clients. Saved me hours of research.",
    "testimonials.carlos":
      "Finally, tax advice that understands the cultural sector. The citations are always accurate.",
    "testimonials.ana": "The instant answers with legal references give me confidence in my tax decisions.",
    "testimonials.maria.role": "Freelance Designer",
    "testimonials.carlos.role": "Independent Musician",
    "testimonials.ana.role": "Content Creator",

    // Final CTA
    "cta.title": "Ready to solve your tax questions?",
    "cta.description":
      "Our AI assistant is specifically trained for the Spanish cultural sector and will provide you with accurate answers based on current legislation.",
    "cta.button": "Start Now →",

    // Footer
    "footer.description": "AI legal assistant specialized in Spanish tax legislation for cultural professionals.",
    "footer.product": "Product",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.api": "API",
    "footer.documentation": "Documentation",
    "footer.legal": "Legal",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.cookies": "Cookies",
    "footer.gdpr": "GDPR",
    "footer.support": "Support",
    "footer.help": "Help Center",
    "footer.contact": "Contact",
    "footer.status": "Service Status",
    "footer.community": "Community",
    "footer.rights": "All rights reserved.",

    // Chat Page
    "chat.title": "Legal Consultation AI",
    "chat.subtitle": "Specialized in Spanish tax legislation",
    "chat.credits.remaining": "Credits remaining",
    "chat.sidebar.chat": "Legal Chat",
    "chat.sidebar.credits": "My Credits",
    "chat.sidebar.docs": "Legal Documents",
    "chat.sidebar.history": "Chat History",
    "chat.sidebar.account": "Account Settings",
    "chat.sidebar.settings": "Preferences",
    "chat.sidebar.help": "Help & Support",
    "chat.sidebar.analytics": "Usage Analytics",
    "chat.sidebar.payment": "Payment & Billing",
    "chat.sidebar.status": "System Status",
    "chat.sidebar.logout": "Sign Out",
    "chat.welcome.title": "How can I help you today?",
    "chat.welcome.description":
      "I am your accounting, tax, labor and legal assistant specialized in the cultural and creative sector and I'm here to help answer your questions.",
    "chat.welcome.examples": "I just need you to tell me who you are, what you do, and what question you'd like answered. The more information you provide, the more complete your response will be.",
    "chat.input.placeholder": "Write your legal question here...",
    "chat.sidebar.view_plans": "View Plans",
    "chat.input.analyzing": "",
    "chat.input.nocredits": "No credits remaining.",
    "chat.input.buycredits": "Buy more credits",
    "chat.input.disclaimer": "The information provided by ARTISTING is informational and should be reviewed by a professional before use.",
    "chat.examples.freelancer": "How should I invoice as a cultural freelancer?",
    "chat.examples.vat": "What VAT do I apply to my artistic services?",
    "chat.examples.deductions": "Can I deduct art material expenses in IRPF?",
    "chat.error.failed": "Failed to send message. Please try again.",
    "chat.error.question_too_short": "Question is too short. Please provide more details.",
    "chat.examples.copyright": "How are copyright royalties taxed?",
    "chat.examples.obligations": "What obligations do I have as a cultural freelancer?",
    "chat.header.new_chat": "New Chat",
    // Credits Page
    "credits.title": "Credits Management",
    "credits.subtitle": "Manage your credits and billing",
    "credits.current.status": "Current Credit Status",
    "credits.usage.history": "Recent Usage History",
    "credits.buy.credits": "Buy Credits",
    "credits.auto.refill": "Auto-refill",
    "credits.payment.method": "Payment Method",
    "credits.billing.history": "Billing History",
    "credits.invoice": "Invoice",
    "credits.download": "Download",
    "credits.purchase": "Purchase Credits",
    "credits.select.plan": "Please select a credit package",
    "credits.purchase.success": "Successfully purchased {credits} credits!",
    "credits.purchase.error": "Failed to purchase credits",

    // Payment Page
    "payment.title": "Payment",
    "payment.subtitle": "Complete your credit purchase",
    "payment.order.summary": "Order Summary",
    "payment.payment.method": "Payment Method",
    "payment.card.number": "Card Number",
    "payment.expiry": "MM/YY",
    "payment.cvc": "CVC",
    "payment.cardholder": "Cardholder Name",
    "payment.billing.address": "Billing Address",
    "payment.country": "Country",
    "payment.postal.code": "Postal Code",
    "payment.complete.payment": "Complete Payment",
    "payment.secure": "Secure Payment",
    "payment.processing": "Processing...",
  // Additional payment strings used in UI text
  "payment.order.package": "{name} - {credits} credits",
  "payment.order.total": "Total",
  "payment.features.immediate": "Immediate access to credits",
  "payment.features.no_commitment": "No long-term commitment",
  "payment.features.support": "Specialized support",
  "payment.features.invoice": "Invoice available",
  "payment.security.notice.title": "Secure checkout",
  "payment.security.notice.desc": "Payments are processed securely by our provider. We do not store your full card details.",

  // Pricing
  "pricing.badge": "Credit Plans",
  "pricing.title": "Pricing",
  "pricing.subtitle": "Choose the plan that best fits your needs",
  "pricing.month": "month",
  "pricing.credits": "credits",
  "pricing.included": "Includes",
  "pricing.upgrade.button": "View Plans",
  "pricing.limitations": "Limitations",
  "pricing.get.started": "Get Started",
  "pricing.select": "Select Plan",
  "pricing.popular": "Popular",
  "pricing.basic.name": "Basic",
  "pricing.basic.description": "Ideal for freelancers and occasional consultations.",
  "pricing.basic.feature1": "50 credits per month",
  "pricing.basic.feature2": "Answers based on Spanish legislation",
  "pricing.basic.feature3": "Email support",
  "pricing.basic.feature4": "Access to consultation history",
  "pricing.basic.limitation1": "No advanced billing",
  "pricing.basic.limitation2": "No priority support",
  "pricing.professional.name": "Professional",
  "pricing.professional.description": "For professionals who need frequent consultations.",
  "pricing.professional.feature1": "200 credits per month",
  "pricing.professional.feature2": "Priority support",
  "pricing.professional.feature3": "Billing and invoice available",
  "pricing.professional.feature4": "Access to usage analytics",
  "pricing.professional.feature5": "More detailed answers",
  "pricing.professional.feature6": "Future integrations",
  "pricing.enterprise.name": "Enterprise",
  "pricing.enterprise.description": "Solution for teams and organizations.",
  "pricing.enterprise.feature1": "500 credits per month",
  "pricing.enterprise.feature2": "Multi-user account",
  "pricing.enterprise.feature3": "Dedicated support",
  "pricing.enterprise.feature4": "Custom integrations",
  "pricing.enterprise.feature5": "SLA by agreement",
  "pricing.enterprise.feature6": "Advanced billing",
  "pricing.enterprise.feature7": "Provisioning and onboarding",
  "pricing.faq.title": "Pricing Questions",
  "pricing.faq.subtitle": "Common questions about our plans",
  "pricing.faq.q1": "Can I change plans later?",
  "pricing.faq.a1": "Yes, you can upgrade or downgrade your plan at any time from the billing section.",
  "pricing.faq.q2": "Are invoices available?",
  "pricing.faq.a2": "Yes, we provide invoices for all payments made on the platform.",
  "pricing.faq.q3": "What happens if I run out of credits?",
  "pricing.faq.a3": "You can purchase additional packages or switch to a higher plan.",
  "pricing.faq.q4": "Do you offer refunds?",
  "pricing.faq.a4": "Refunds are handled case-by-case according to our refund policy.",

  // Forgot / Reset
  "forgot.title": "Forgot Password",
  "forgot.description": "Enter your email and we'll send a link to reset your password.",
  "forgot.sending": "Sending...",
  "forgot.send_link": "Send reset link",
  "forgot.success": "Link sent",
  "forgot.success_message": "If an account exists, you'll receive an email with the reset link.",
  "forgot.error": "Error sending reset link",
  "forgot.remember": "Remembered your password?",
  "forgot.email.placeholder": "you@example.com",

  // Auth / Reset password keys
  "auth.reset.title": "Reset Password",
  "auth.reset.token_required": "A token is required in the URL",
  "auth.reset.request_new": "Request new link",
  "auth.reset.invalid_link": "Invalid link",
  "auth.reset.invalid_token_message": "The reset link is invalid or has expired.",
  "auth.reset.link_expired": "The link has expired or is invalid.",
  "auth.reset.success": "Password reset successfully",
  "auth.reset.error": "Error resetting password",
  "auth.reset.resetting": "Resetting...",
  "auth.reset.submit": "Reset password",
  "auth.reset.remember_password": "Remembered your password?",

    // Settings
    "settings.title": "Settings",
    "settings.general": "General",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.notifications": "Notifications",
    "settings.privacy": "Privacy",
    "settings.data.export": "Export Data",
    "settings.data.delete": "Delete Data",
    "settings.data.export.success": "Data exported successfully!",
    "settings.data.export.error": "Failed to export data",
    "settings.data.delete.success": "Data deleted successfully!",
    "settings.data.delete.error": "Failed to delete data",
    "settings.data.delete.confirm": "Are you sure you want to delete all your data? This action cannot be undone.",
    "settings.account.delete.success": "Account deleted successfully!",
    "settings.account.delete.error": "Failed to delete account",
    "settings.account.delete.confirm": "Are you sure you want to delete your account? This action cannot be undone.",


    // History Page
    "history.title": "Consultation History",
    "history.subtitle": "Review your past legal consultations and answers",
    "history.search.placeholder": "Search consultations...",
    "history.filter.all": "All Topics",
    "history.filter.vat": "VAT",
    "history.filter.irpf": "IRPF",
    "history.filter.billing": "Billing",
    "history.filter.deductions": "Deductions",
    "history.sort.newest": "Newest",
    "history.sort.oldest": "Oldest",
    "history.sort.relevant": "Most Relevant",
    "history.no.results": "No consultations found",
    "history.load.more": "Load More",
    "history.export": "Export History",
    
    // Auth Pages
    "auth.login.title": "Sign In",
    "auth.login.subtitle": "Access the platform for the cultural and creative sector",
    "auth.login.email": "Email ",
    "auth.login.password": "Password",
    "auth.login.show.password": "Show Password",
    "auth.login.hide.password": "Hide Password",
    "auth.login.forgot.password": "Forgot your password?",
    "auth.login.submit": "Login",
    "auth.login.no.account": "Don't have an account?",
    "auth.login.signup.link": "Sign up here",
    "auth.signup.title": "Create Account",
    "auth.signup.subtitle": "Join the leading platform for the cultural and creative sector",
    "auth.signup.first.name": "First Name",
    "auth.signup.last.name": "Last Name",
    "auth.signup.email": "Email ",
    "auth.signup.password": "Password",
    "auth.signup.confirm.password": "Confirm Password",
    "auth.signup.terms": "Terms and Conditions",
    "auth.signup.submit": "Create Account",
    "auth.signup.have.account": "Already have an account?",
    "auth.signup.login.link": "Login",
    "auth.error.passwords.mismatch": "Passwords do not match",
    "auth.error.accept.terms": "You must accept the Terms and Conditions",
    "auth.error.create.account": "Error creating account",
    "auth.error.login.failed": "Login failed",
    "auth.login.success": "Successfully signed in!",
    "auth.signup.success": "Account created successfully!",
    "auth.tagline": "Intelligent Legal Assistant",
    "auth.verifying_access": "Verifying access...",
    "auth.please_wait_session": "Please wait while we verify your session",

    //Chat Popup
      "chat.credits.title": "You’ve used up your trial credits.",
      "chat.credits.message": "Activate your subscription to continue receiving professional legal assistance for the cultural and creative sector.",
      "chat.credits.subscribe": "Subscribe Now",
      "chat.credits.dismiss": "Dismiss",



    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.last.updated": "Last updated",
    "privacy.date": "January 1, 2024",
    "privacy.introduction.title": "Introduction",
    "privacy.introduction.content": "ARTISTING is committed to protecting your privacy and personal data. This Privacy Policy explains how we collect, use, store, and protect your information when you use our AI-powered tax assistance services.",
    "privacy.data.collection.title": "Data Collection",
    "privacy.data.collection.intro": "We collect the following types of information:",
    "privacy.data.collection.item1": "Account information (name, email, billing details)",
    "privacy.data.collection.item2": "Usage data (questions asked, features used, session duration)",
    "privacy.data.collection.item3": "Technical data (IP address, browser type, device information)",
    "privacy.data.collection.item4": "Communication data (support requests, feedback)",
    "privacy.data.collection.item5": "Payment information (processed securely through third-party providers)",
    "privacy.data.usage.title": "How We Use Your Data",
    "privacy.data.usage.intro": "Your data is used to:",
    "privacy.data.usage.item1": "Provide and improve our AI tax assistance services",
    "privacy.data.usage.item2": "Process payments and manage your account",
    "privacy.data.usage.item3": "Communicate with you about service updates and support",
    "privacy.data.usage.item4": "Comply with legal obligations and prevent fraud",
    "privacy.data.sharing.title": "Data Sharing",
    "privacy.data.sharing.content": "We do not sell your personal data. We may share data with trusted service providers who help us operate our services, and only when required by law or to protect our rights and users' safety.",
    "privacy.data.security.title": "Data Security",
    "privacy.data.security.content": "We implement industry-standard security measures including encryption, secure servers, and regular security audits to protect your data from unauthorized access, alteration, or destruction.",
    "privacy.cookies.title": "Cookies and Tracking",
    "privacy.cookies.content": "We use cookies and similar technologies to enhance your experience, analyze usage patterns, and provide personalized services. You can control cookie preferences through your browser settings.",
    "privacy.user.rights.title": "Your Rights",
    "privacy.user.rights.intro": "Under GDPR and Spanish data protection laws, you have the right to:",
    "privacy.user.rights.item1": "Access your personal data and request copies",
    "privacy.user.rights.item2": "Correct inaccurate or incomplete information",
    "privacy.user.rights.item3": "Request deletion of your data (right to be forgotten)",
    "privacy.user.rights.item4": "Restrict or object to data processing",
    "privacy.user.rights.item5": "Data portability and withdrawal of consent",
    "privacy.data.retention.title": "Data Retention",
    "privacy.data.retention.content": "We retain your data only as long as necessary to provide services and comply with legal obligations. Account data is typically retained for 3 years after account closure, unless longer retention is required by law.",
    "privacy.international.title": "International Transfers",
    "privacy.international.content": "Your data may be processed in countries outside the EU. We ensure adequate protection through appropriate safeguards such as Standard Contractual Clauses and adequacy decisions.",
    "privacy.changes.title": "Policy Changes",
    "privacy.changes.content": "We may update this Privacy Policy periodically. Significant changes will be communicated via email and through our service. Continued use after changes indicates acceptance of the updated policy.",
    "privacy.contact.title": "Contact Us",
    "privacy.contact.content": "For privacy-related questions or to exercise your rights, please contact our Data Protection Officer:",
    "privacy.back.home": "Back to Home",

    // Cookies Policy
    "cookies.title": "Cookie Policy",
    "cookies.last.updated": "Last updated",
    "cookies.date": "January 1, 2024",
    "cookies.what.are.title": "What are Cookies?",
    "cookies.what.are.content": "Cookies are small text files stored on your device when you visit our website. They help us provide you with a better experience by remembering your preferences and analyzing how you use our service.",
    "cookies.how.we.use.title": "How We Use Cookies",
    "cookies.how.we.use.content": "We use cookies to enhance your experience, provide personalized content, analyze website traffic, and improve our services. All cookies are used in accordance with applicable privacy laws.",
    "cookies.types.title": "Types of Cookies We Use",
    "cookies.essential.name": "Essential Cookies",
    "cookies.essential.description": "These cookies are necessary for the website to function properly and cannot be disabled.",
    "cookies.essential.duration": "Session or up to 1 year",
    "cookies.essential.example1": "Authentication tokens",
    "cookies.essential.example2": "Security preferences",
    "cookies.essential.example3": "Language settings",
    "cookies.analytics.name": "Analytics Cookies",
    "cookies.analytics.description": "These cookies help us understand how visitors interact with our website.",
    "cookies.analytics.duration": "Up to 2 years",
    "cookies.analytics.example1": "Google Analytics",
    "cookies.analytics.example2": "Usage statistics",
    "cookies.analytics.example3": "Performance metrics",
    "cookies.functional.name": "Functional Cookies",
    "cookies.functional.description": "These cookies enable enhanced functionality and personalization.",
    "cookies.functional.duration": "Up to 1 year",
    "cookies.functional.example1": "Theme preferences",
    "cookies.functional.example2": "Chat history",
    "cookies.functional.example3": "User preferences",
    "cookies.required": "Required",
    "cookies.duration": "Duration",
    "cookies.examples": "Examples",
    "cookies.third.party.title": "Third-Party Cookies",
    "cookies.third.party.content": "We may use third-party services that set their own cookies:",
    "cookies.third.party.item1": "Payment processors for secure transactions",
    "cookies.third.party.item2": "Analytics providers for usage insights",
    "cookies.third.party.item3": "Support chat services for customer assistance",
    "cookies.manage.title": "Managing Cookies",
    "cookies.manage.content": "You can control and manage cookies through your browser settings. Please note that disabling certain cookies may affect website functionality.",
    "cookies.browser.settings": "Browser Settings",
    "cookies.browser.chrome": "Chrome: Settings > Privacy and Security > Cookies",
    "cookies.browser.firefox": "Firefox: Settings > Privacy & Security > Cookies",
    "cookies.browser.safari": "Safari: Preferences > Privacy > Cookies",
    "cookies.browser.edge": "Edge: Settings > Privacy > Cookies",
    "cookies.consent.title": "Cookie Consent",
    "cookies.consent.content": "By continuing to use our website, you consent to our use of cookies as described in this policy. You can withdraw consent at any time by adjusting your browser settings.",
    "cookies.updates.title": "Policy Updates",
    "cookies.updates.content": "We may update this Cookie Policy periodically. Any changes will be posted on this page with an updated revision date.",
    "cookies.contact.title": "Contact Us",
    "cookies.contact.content": "If you have questions about our use of cookies, please contact us at privacy@ovra-ai.com.",
    "cookies.back.home": "Back to Home",

    // GDPR
    "gdpr.title": "GDPR Compliance",
    "gdpr.subtitle": "Your data protection rights under European law",
    "gdpr.what.is.title": "What is GDPR?",
    "gdpr.what.is.content": "The General Data Protection Regulation (GDPR) is a comprehensive data protection law that gives individuals control over their personal data and simplifies the regulatory environment for businesses.",
    "gdpr.our.commitment.title": "Our Commitment",
    "gdpr.our.commitment.content": "ARTISTING is fully committed to GDPR compliance. We implement privacy by design principles and ensure your data rights are respected:",
    "gdpr.commitment.item1": "Transparent data processing with clear consent",
    "gdpr.commitment.item2": "Secure data storage with encryption and access controls",
    "gdpr.commitment.item3": "Regular privacy impact assessments",
    "gdpr.commitment.item4": "Prompt breach notification procedures",
    "gdpr.your.rights.title": "Your Data Rights",
    "gdpr.your.rights.subtitle": "Under GDPR, you have the following rights regarding your personal data:",
    "gdpr.right.access.title": "Right of Access",
    "gdpr.right.access.description": "You can request information about what personal data we hold about you.",
    "gdpr.right.access.action": "Contact us to request a copy of your data",
    "gdpr.right.rectification.title": "Right to Rectification",
    "gdpr.right.rectification.description": "You can request correction of inaccurate or incomplete personal data.",
    "gdpr.right.rectification.action": "Update your profile or contact support for corrections",
    "gdpr.right.erasure.title": "Right to Erasure (Right to be Forgotten)",
    "gdpr.right.erasure.description": "You can request deletion of your personal data under certain circumstances.",
    "gdpr.right.erasure.action": "Submit a deletion request through your account settings",
    "gdpr.right.portability.title": "Right to Data Portability",
    "gdpr.right.portability.description": "You can request your data in a structured, machine-readable format.",
    "gdpr.right.portability.action": "Export your data from your account dashboard",
    "gdpr.right.restriction.title": "Right to Restriction of Processing",
    "gdpr.right.restriction.description": "You can request limitation of how we process your data.",
    "gdpr.right.restriction.action": "Contact our DPO to discuss processing restrictions",
    "gdpr.right.objection.title": "Right to Object",
    "gdpr.right.objection.description": "You can object to certain types of data processing.",
    "gdpr.right.objection.action": "Opt-out through account settings or contact support",
    "gdpr.how.to.exercise": "How to exercise this right:",
    "gdpr.legal.basis.title": "Legal Basis for Processing",
    "gdpr.legal.basis.content": "We process your personal data based on the following legal grounds:",
    "gdpr.legal.basis.item1": "Consent: For marketing communications and optional features",
    "gdpr.legal.basis.item2": "Contract: To provide our tax assistance services",
    "gdpr.legal.basis.item3": "Legitimate Interest: For service improvement and fraud prevention",
    "gdpr.legal.basis.item4": "Legal Obligation: For tax records and compliance requirements",
    "gdpr.data.transfers.title": "International Data Transfers",
    "gdpr.data.transfers.content": "When we transfer your data outside the EU, we ensure adequate protection through approved mechanisms such as Standard Contractual Clauses and adequacy decisions by the European Commission.",
    "gdpr.complaints.title": "Right to Lodge a Complaint",
    "gdpr.complaints.content": "If you believe we have not handled your data properly, you have the right to lodge a complaint with your local supervisory authority:",
    "gdpr.supervisory.authority": "Spanish Supervisory Authority",
    "gdpr.contact.dpo.title": "Contact Our Data Protection Officer",
    "gdpr.contact.dpo.content": "For any GDPR-related questions or to exercise your rights, contact our Data Protection Officer:",
    "gdpr.response.time": "We will respond to your request within 30 days",
    "gdpr.exercise.rights.title": "Exercise Your Rights",
    "gdpr.exercise.rights.content": "Ready to exercise your data protection rights? Contact us or review our privacy policy for more information.",
    "gdpr.contact.us": "Contact Us",
    "gdpr.privacy.policy": "Privacy Policy",
    "gdpr.back.home": "Back to Home",

    // Help Center
    "help.title": "Help Center",
    "help.subtitle": "Find answers to your questions and get the support you need",
    "help.search.placeholder": "Search for help articles...",
    "help.search": "Search",
    "help.popular.title": "Popular Articles",
    "help.popular.subtitle": "Most frequently accessed help topics",
    "help.popular.article1": "How to get started with ARTISTING",
    "help.popular.article2": "Understanding your tax obligations as a freelancer",
    "help.popular.article3": "Managing your account and billing",
    "help.popular.article4": "Interpreting AI responses and legal advice",
    "help.popular.article5": "Privacy and data security",
    "help.categories.title": "Help Categories",
    "help.categories.subtitle": "Browse help topics by category",
    "help.getting.started.title": "Getting Started",
    "help.getting.started.description": "Learn the basics of using ARTISTING",
    "help.getting.started.article1": "Creating your account",
    "help.getting.started.article2": "Your first tax consultation",
    "help.getting.started.article3": "Understanding AI responses",
    "help.getting.started.article4": "Setting up your profile",
    "help.billing.title": "Billing & Subscriptions",
    "help.billing.description": "Manage your payments and subscription",
    "help.billing.article1": "Subscription plans and pricing",
    "help.billing.article2": "Payment methods and billing",
    "help.billing.article3": "Upgrading or downgrading plans",
    "help.billing.article4": "Refunds and cancellations",
    "help.privacy.title": "Privacy & Security",
    "help.privacy.description": "Learn about data protection and security",
    "help.privacy.article1": "How we protect your data",
    "help.privacy.article2": "GDPR compliance and your rights",
    "help.privacy.article3": "Cookie policy and preferences",
    "help.privacy.article4": "Account security best practices",
    "help.account.title": "Account Management",
    "help.account.description": "Manage your account settings and preferences",
    "help.account.article1": "Updating your profile information",
    "help.account.article2": "Changing your password",
    "help.account.article3": "Language and notification settings",
    "help.account.article4": "Deleting your account",
    "help.contact.title": "Still Need Help?",
    "help.contact.subtitle": "Get in touch with our support team",
    "help.contact.chat": "Live Chat",
    "help.contact.chat.description": "Chat with our support team",
    "help.contact.chat.button": "Start Chat",
    "help.contact.email": "Email Support",
    "help.contact.email.description": "Send us a detailed message",
    "help.contact.email.button": "Contact Us",
    "help.contact.guides": "User Guides",
    "help.contact.guides.description": "Detailed documentation",
    "help.contact.guides.button": "View Guides",

    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with our team. We're here to help with any questions or concerns.",
    "contact.form.title": "Send us a Message",
    "contact.form.description": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.form.name": "Full Name",
    "contact.form.name.placeholder": "Enter your full name",
    "contact.form.email": "Email Address",
    "contact.form.email.placeholder": "Enter your email address",
    "contact.form.category": "Category",
    "contact.form.category.placeholder": "Select a category",
    "contact.form.subject": "Subject",
    "contact.form.subject.placeholder": "Brief description of your inquiry",
    "contact.form.message": "Message",
    "contact.form.message.placeholder": "Describe your question or concern in detail...",
    "contact.form.submit": "Send Message",
    "contact.form.validation.required": "Please fill in all required fields",
    "contact.form.validation.email": "Please enter a valid email address",
    "contact.form.success": "Message sent successfully! We'll get back to you soon.",
    "contact.form.error": "Failed to send message. Please try again.",
    "contact.category.general": "General Inquiry",
    "contact.category.support": "Technical Support",
    "contact.category.bug": "Bug Report",
    "contact.category.feature": "Feature Request",
    "contact.info.title": "Contact Information",
    "contact.email.title": "Email Support",
    "contact.email.description": "Send us an email anytime",
    "contact.email.action": "We typically respond within 24 hours",
    "contact.phone.title": "Phone Support",
    "contact.phone.description": "Call us during business hours",
    "contact.phone.action": "Monday to Friday, 9 AM - 6 PM CET",
    "contact.address.title": "Office Address",
    "contact.address.description": "Visit us in person",
    "contact.address.action": "By appointment only",
    "contact.hours.title": "Business Hours",
    "contact.hours.description": "When we're available",
    "contact.hours.value": "Monday - Friday: 9:00 AM - 6:00 PM CET",
    "contact.faq.title": "Frequently Asked Questions",
    "contact.faq.description": "Find quick answers to common questions",
    "contact.faq.button": "Visit Help Center",

    // Status Page
    "status.title": "Service Status",
    "status.subtitle": "Real-time status and uptime monitoring for all ARTISTING services",
    "status.overall": "Overall Status",
    "status.operational": "Operational",
    "status.degraded": "Degraded Performance",
    "status.outage": "Service Outage",
    "status.resolved": "Resolved",
    "status.services.title": "Service Status",
    "status.services.subtitle": "Current status of all our services",
    "status.service.api": "API Service",
    "status.service.api.description": "Core API for all ARTISTING functionality",
    "status.service.ai": "AI Processing",
    "status.service.ai.description": "AI model inference and response generation",
    "status.service.database": "Database",
    "status.service.database.description": "Data storage and retrieval systems",
    "status.service.web": "Web Application",
    "status.service.web.description": "Frontend web application and user interface",
    "status.uptime": "Uptime",
    "status.response.time": "Response Time",
    "status.incidents.title": "Recent Incidents",
    "status.incidents.subtitle": "Past incidents and their resolution status",
    "status.incident.1.title": "AI Response Delays",
    "status.incident.1.description": "Temporary delays in AI response generation due to high demand",
    "status.incident.2.title": "Database Maintenance",
    "status.incident.2.description": "Scheduled maintenance caused brief service interruption",
    "status.duration": "Duration",
    "status.affected.services": "Affected Services",
    "status.no.incidents.title": "No Recent Incidents",
    "status.no.incidents.description": "All systems have been running smoothly with no reported incidents in the past 30 days.",
    "status.subscribe.title": "Stay Updated",
    "status.subscribe.description": "Subscribe to status updates and get notified about service changes",
    "status.subscribe.button": "Subscribe to Updates",

    // Community Page
    "community.title": "Community",
    "community.subtitle": "Join thousands of cultural professionals sharing knowledge and experiences",
    "community.join.button": "Join Community",
    "community.explore.button": "Explore Discussions",
    "community.stats.members": "Active Members",
    "community.stats.members.description": "Cultural professionals in our community",
    "community.stats.discussions": "Discussions",
    "community.stats.discussions.description": "Active conversations and topics",
    "community.stats.resources": "Shared Resources",
    "community.stats.resources.description": "Guides, templates, and tools",
    "community.stats.experts": "Tax Experts",
    "community.stats.experts.description": "Verified professionals providing guidance",
    "community.platforms.title": "Join Our Community",
    "community.platforms.subtitle": "Connect with us on your preferred platform",
    "community.discord.description": "Real-time chat with fellow professionals and experts",
    "community.github.description": "Contribute to open-source tools and resources",
    "community.twitter.description": "Latest updates and quick tips",
    "community.linkedin.description": "Professional networking and industry insights",
    "community.primary": "Primary",
    "community.members": "members",
    "community.join": "Join",
    "community.discussions.title": "Featured Discussions",
    "community.discussions.subtitle": "Popular topics and conversations",
    "community.discussion.1.title": "New VAT regulations for digital services - What you need to know",
    "community.discussion.2.title": "Freelancer tax deductions: Complete guide for 2024",
    "community.discussion.3.title": "Setting up your first invoice as a cultural professional",
    "community.category.tax": "Tax Advice",
    "community.category.freelance": "Freelancing",
    "community.category.legal": "Legal Questions",
    "community.by": "by",
    "community.view.all": "View All Discussions",
    "community.events.title": "Upcoming Events",
    "community.events.subtitle": "Join our webinars, workshops, and Q&A sessions",
    "community.event.1.title": "Tax Planning Workshop for Creative Professionals",
    "community.event.2.title": "Understanding Spanish VAT: Interactive Session",
    "community.event.3.title": "Monthly Q&A with Tax Experts",
    "community.event.webinar": "Webinar",
    "community.event.workshop": "Workshop",
    "community.event.qa": "Q&A Session",
    "community.registered": "registered",
    "community.register": "Register Now",
    "community.cta.title": "Ready to Join Our Community?",
    "community.cta.description": "Connect with fellow professionals, share experiences, and get expert advice",
    "community.cta.join": "Join Community",
    "community.cta.signup": "Regístrate for ARTISTING",

    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.last.updated": "Last updated",
    "terms.date": "January 1, 2024",
    "terms.back.home": "Back to Home",
    "terms.acceptance.title": "Acceptance of Terms",
    "terms.acceptance.content": "By accessing and using ARTISTING services, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
    "terms.description.title": "Service Description",
    "terms.description.content": "ARTISTING provides AI-powered tax assistance services specifically designed for Spanish cultural professionals. Our service offers legal guidance based on current Spanish legislation, including VAT, IRPF, and other relevant tax regulations.",
    "terms.user.obligations.title": "User Obligations",
    "terms.user.obligations.intro": "As a user of ARTISTING, you agree to:",
    "terms.user.obligations.item1": "Provide accurate and truthful information when using our services",
    "terms.user.obligations.item2": "Use the service only for lawful purposes and in accordance with these terms",
    "terms.user.obligations.item3": "Not attempt to circumvent any security measures or access restrictions",
    "terms.user.obligations.item4": "Respect the intellectual property rights of ARTISTING and third parties",
    "terms.intellectual.property.title": "Intellectual Property",
    "terms.intellectual.property.content": "All content, features, and functionality of ARTISTING, including but not limited to text, graphics, logos, and software, are owned by ARTISTING and are protected by international copyright, trademark, and other intellectual property laws.",
    "terms.privacy.title": "Privacy and Data Protection",
    "terms.privacy.content": "Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information when you use our services. By using ARTISTING, you consent to the collection and use of information in accordance with our Privacy Policy.",
    "terms.payment.title": "Payment and Billing",
    "terms.payment.content": "ARTISTING operates on a credit-based system. Users purchase credits to access AI consultations. All payments are processed securely, and billing terms are clearly displayed before purchase. Refunds are available in accordance with our refund policy.",
    "terms.limitation.title": "Limitation of Liability",
    "terms.limitation.content": "ARTISTING provides information for educational and guidance purposes only. While we strive for accuracy, our AI responses should not replace professional legal advice. Users are responsible for verifying information and consulting with qualified professionals for specific legal matters.",
    "terms.termination.title": "Termination",
    "terms.termination.content": "We reserve the right to terminate or suspend your account and access to our services at our sole discretion, without notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties.",
    "terms.changes.title": "Changes to Terms",
    "terms.changes.content": "We reserve the right to modify these terms at any time. We will notify users of any material changes via email or through our service. Continued use of ARTISTING after changes constitutes acceptance of the new terms.",
    "terms.contact.title": "Contact Information",
    "terms.contact.content": "If you have any questions about these Terms of Service, please contact us:",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("es") // Set Spanish as default

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "es")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export async function getConversations(page = 1, limit = 20) {
  // If you have an auth helper, add Authorization header. For now perform an unauthenticated fetch as a safe fallback.
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/chat/sessions/?page=${page}&limit=${limit}`)
  return res.json()
}
